services:
  redis:
    container_name: REDIS
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning

  ngrok:
    container_name: NGROK
    image: ngrok/ngrok
    command: http PROXY:80 --domain=allowing-llama-seemingly.ngrok-free.app
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    networks:
      - app-network
    restart: unless-stopped

  nginx:
    container_name: PROXY
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    container_name: CLIENT
    build:
      context: ./CLIENT
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network
    working_dir: /app
    volumes:
      - ./CLIENT:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=true
      - WDS_SOCKET_PORT=3000
      - BROWSER=none
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    restart: unless-stopped
    stdin_open: true
    tty: true

  backend:
    container_name: SERVER
    build:
      context: ./SERVER
      dockerfile: Dockerfile
    ports:
      - "8443:8443"
    networks:
      - app-network
    working_dir: /app
    volumes:
      - ./SERVER:/app
      - /app/node_modules
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  redis_data:
